# Generated by Django 2.1 on 2019-08-06 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tramino', '0002_auto_20190806_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventapplypool',
            name='event_post_id',
        ),
        migrations.RemoveField(
            model_name='eventapplypool',
            name='guest_team_id',
        ),
        migrations.RemoveField(
            model_name='eventpostpool',
            name='event_host_team',
        ),
        migrations.RemoveField(
            model_name='favoriteeventpool',
            name='event_post_id',
        ),
        migrations.RemoveField(
            model_name='favoriteeventpool',
            name='guest_team_id',
        ),
        migrations.RemoveField(
            model_name='favoriteteampool',
            name='guest_team_id',
        ),
        migrations.RemoveField(
            model_name='favoriteteampool',
            name='host_team_id',
        ),
        migrations.RemoveField(
            model_name='pastgamerecords',
            name='register_team_id',
        ),
        migrations.DeleteModel(
            name='EventApplyPool',
        ),
        migrations.DeleteModel(
            name='EventPostPool',
        ),
        migrations.DeleteModel(
            name='FavoriteEventPool',
        ),
        migrations.DeleteModel(
            name='FavoriteTeamPool',
        ),
        migrations.DeleteModel(
            name='PastGameRecords',
        ),
    ]
