# Generated by Django 2.1 on 2019-08-06 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramino', '0005_auto_20190806_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventapplypool',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='eventpostpool',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='favoriteeventpool',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='favoriteteampool',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pastgamerecords',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
