# Generated by Django 2.1 on 2019-08-17 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tramino', '0005_eventpostcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpostcomment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_post_comments', to='tramino.TeamInformations'),
        ),
        migrations.AlterField(
            model_name='eventpostcomment',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tramino.TeamInformations'),
        ),
    ]
