# Generated by Django 2.1 on 2019-08-06 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tramino', '0006_auto_20190806_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pastgamerecords',
            name='game_data',
        ),
    ]
