# Generated by Django 2.1 on 2019-08-18 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tramino', '0007_auto_20190817_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpostcomment',
            name='guest_team_id',
        ),
        migrations.RemoveField(
            model_name='eventpostcomment',
            name='post',
        ),
        migrations.DeleteModel(
            name='EventPostComment',
        ),
    ]
