# Generated by Django 2.1 on 2019-08-06 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramino', '0007_remove_pastgamerecords_game_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastgamerecords',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='date published'),
        ),
    ]
