# Generated by Django 2.1 on 2019-08-06 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tramino', '0008_pastgamerecords_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pastgamerecords',
            old_name='date',
            new_name='game_date',
        ),
    ]
