# Generated by Django 2.1 on 2019-08-28 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramino', '0009_auto_20190829_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpostpool',
            name='event_place',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='eventpostpool',
            name='parking',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
