# Generated by Django 2.1 on 2019-08-06 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramino', '0009_auto_20190806_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastgamerecords',
            name='game_date',
            field=models.DateField(verbose_name='date published'),
        ),
    ]
