# Generated by Django 2.1 on 2019-08-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramino', '0010_auto_20190806_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaminformations',
            name='team_picture',
            field=models.ImageField(default='SOME STRING', upload_to='image/'),
        ),
    ]
