# Generated by Django 2.1 on 2019-08-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramino', '0010_auto_20190829_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaminformations',
            name='activity_place',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
