# Generated by Django 2.1 on 2019-08-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramino', '0011_teaminformations_team_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpostpool',
            name='event_picture',
            field=models.ImageField(default='SOME STRING', upload_to='image/'),
        ),
        migrations.AddField(
            model_name='teaminformations',
            name='commander_picture',
            field=models.ImageField(default='SOME STRING', upload_to='image/'),
        ),
    ]
