# Generated by Django 2.1 on 2019-08-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramino', '0011_auto_20190829_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaminformations',
            name='achievement',
            field=models.CharField(blank=True, choices=[['全国大会出場常連レベル', '全国大会出場常連レベル'], ['全国大会出場レベル', '全国大会出場レベル'], ['都道府県大会常連レベル', '都道府県大会常連レベル'], ['都道府県大会出場レベル', '都道府県大会出場レベル'], ['地区大会入賞レベル', '地区大会入賞レベル'], ['地区大会常連レベル', '地区大会常連レベル']], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='teaminformations',
            name='club_name',
            field=models.CharField(choices=[['サッカー', 'サッカー'], ['野球', '野球'], ['ソフトボール', 'ソフトボール'], ['テニス', 'テニス'], ['ソフトテニス', 'ソフトテニス'], ['バレーボール', 'バレーボール'], ['バスケ', 'バスケ'], ['バドミントン', 'バドミントン'], ['柔道', '柔道'], ['剣道', '剣道'], ['卓球', '卓球']], max_length=30),
        ),
    ]
