# Generated by Django 2.1 on 2019-08-08 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramino', '0012_auto_20190806_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpostpool',
            name='event_picture',
            field=models.ImageField(blank=True, default='SOME STRING', null=True, upload_to='image/'),
        ),
    ]
