# Generated by Django 2.1 on 2019-08-08 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tramino', '0013_auto_20190808_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpostpool',
            name='event_picture',
        ),
    ]
