# Generated by Django 2.1 on 2019-08-08 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramino', '0014_remove_eventpostpool_event_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpostpool',
            name='event_picture',
            field=models.ImageField(blank=True, default='SOME STRING', null=True, upload_to='image/'),
        ),
    ]
