# Generated by Django 2.1 on 2019-08-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramino', '0015_eventpostpool_event_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpostpool',
            name='event_picture',
            field=models.ImageField(blank=True, default='SOME STRING', null=True, upload_to='event/'),
        ),
        migrations.AlterField(
            model_name='teaminformations',
            name='commander_picture',
            field=models.ImageField(default='SOME STRING', upload_to='team/commander/'),
        ),
        migrations.AlterField(
            model_name='teaminformations',
            name='team_picture',
            field=models.ImageField(default='SOME STRING', upload_to='team/team/'),
        ),
    ]
