# Generated by Django 2.1 on 2019-08-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramino', '0016_auto_20190808_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpostpool',
            name='event_picture',
            field=models.ImageField(blank=True, null=True, upload_to='event/'),
        ),
    ]
