# Generated by Django 2.1 on 2019-08-08 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramino', '0017_auto_20190808_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpostpool',
            name='event_picture',
            field=models.ImageField(blank=True, default='SOME STRING', null=True, upload_to='event/'),
        ),
    ]
