# Generated by Django 2.1 on 2019-08-08 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tramino', '0018_auto_20190808_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teaminformations',
            name='team_picture',
        ),
    ]
