# Generated by Django 2.1 on 2019-08-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramino', '0019_remove_teaminformations_team_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaminformations',
            name='team_picture',
            field=models.ImageField(default='SOME STRING', upload_to='team/team/'),
        ),
    ]
